# Gplatform Global deployment for pro environment properties
oozie:
  url: "http://euhsuf0093fxmpp.serv.dc.tg.telefonica:11000/oozie"

hadoop:
  cluster:
    namenode:   "hdfs://euhsuf0092fxmpp.serv.dc.tg.telefonica"
    jobtracker: "euhsuf0092fxmpp.serv.dc.tg.telefonica:8050"
    krbenabled: true

hive:
  thrift: "thrift://euhsuf0093fxmpp.serv.dc.tg.telefonica:9083"
  krbprincipal: "hive/euhsuf0093fxmpp.serv.dc.tg.telefonica@HDP.PRE"

db:
  host:         "10.101.139.207"
  port:         3306
  schema_homog: "{{ project.prefix }}gbic_global_homog"
  schema:       "{{ project.prefix }}gbic_global_bnss"
  schema_dq:    "{{ project.prefix }}gbic_data_quality"
  user:         "indust_master"
  pass:         "indust_master_preproQPy3jhEKKLi"

nodes:
  client:
    inbox: "/sftp"

slack:
  alarms:
    ingest:         "https://hooks.slack.com/services/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"
    genfile:        "https://hooks.slack.com/services/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"
    workflow:       "https://hooks.slack.com/services/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"
    export:         "https://hooks.slack.com/services/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"

proxy:
  required: true
  http:  "http://10.93.0.169:8080"
  https: "https://10.93.0.169:8080"
